name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install
      - name: Build assets
        run: npm run prod
      - name: Build Jigsaw site
        run: ./vendor/bin/jigsaw build production
      - name: Create CNAME File
        run: echo "docs.cierra.dev" >> build_production/CNAME
      - name: Stage Files
        run: git add -f build_production
      - name: Commit files
        run: |
          git config --local user.email "jasim@cierra.de"
          git config --local user.name "Jasim Uddin"
          git commit -m "Build for deploy"
      - name: Publish
        run: |
          git subtree split --prefix build_production -b gh-pages
          git push -f origin gh-pages:gh-pages
          git branch -D gh-pages
